### ISSUE TITLE
Entity handler

### ISSUE THREAD

**Issue by Gabin-85** [Gabin-85/Me-llamo-dio#10]
A piece of code that can manage entities like the scene handler does with maps.
It load, unload and can save the position of every entity in a save file.

[This needs the save handler]

**Comment by Gabin-85** [comment]
Probably different from what I expect.
I don't think we need this actually.
It's possible that the sceneHandler handle also entities.

If needed we can reopen this issue but not now.

**Comment by Gabin-85** [comment]
The entityHandler just handle all entities : the load, the unload/save, the update & the displaying.

**Comment by symsym-1629** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Entity Toolbox](https://trello.com/c/BL9XXyHr/15-entity-toolbox)
