### ISSUE TITLE
Save handler

### ISSUE THREAD

**Issue by Gabin-85** [Gabin-85/Me-llamo-dio#11]
A piece of code that can save information in a save folder.
You can manage it to load different saves or load with no save.

(It will take some time so please stop any issue during this one)

**Comment by Gabin-85** [comment]
Actually it's just a crappy test and it need  an entire rewrite

**Comment by Gabin-85** [comment]
The save handler is actually finished and just need to be tested

**Comment by symsym-1629** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Save system](https://trello.com/c/aZZWX6xE/16-save-system)

**Comment by Gabin-85** [comment]
Finished
